### ISSUE TITLE
GOA/AI Shapefile input produces NAs

### ISSUE THREAD

**Issue by Jason-Conner-NOAA** [oceanconner/simfish#3]
We need to identify the appropriate shapefiles and correctly assign prediction grid cells to the input polygon.

**Comment by Lewis-Barnett-NOAA** [comment]
It appears that this commit should have fixed the issue if I understand the problem correctly: https://github.com/oceanconner/simfish/commit/3995d50656aa3fea78b9917e10669459d1002eda
